esphome:
  name: clockwise
  friendly_name: Clockwise Mario

  platformio_options:
    lib_deps:
      - Networking
      - WiFi
      - EEPROM
            
      - ropg/ezTime
      - adafruit/Adafruit BusIO 
      - adafruit/Adafruit GFX Library  
      - https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA
    build_flags:
      - -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
      - -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WiFi/src
      - -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/EEPROM/src
    # Optional but recommended: clean dependency mode
    lib_ldf_mode: chain+      

# Pull the glue component from your GitHub repo (Option B)
external_components:
  - source: github://aschoelzhorn/clockwise-esphome@main
    #refresh: 1s only for debug

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  
  ap:
    ssid: "CW Mario Fallback"
    password: "12345678"

# Time provider (the face reads time via a shim from this SNTP clock)
time:
  - platform: sntp
    id: sntp_time

# Instantiate the Mario face (our external component)
# This internally does:
#   clockface = new Clockface(dma_display);
#   clockface->setup(&CWDateTimeShim); // ESPHome time
#   clockface->update();
clockwise_mario_ext:
  id: marioclk
  width: 64
  height: 64
  brightness: 180
  time_id: sntp_time
  driver: FM6126A
  clock_phase: false       # flip to false if you see a 1-column shift
  pins:                    # Huidu HD-WF2 (X1) → HUB75E (64x64)
    r1: 2
    g1: 6
    b1: 10
    r2: 3
    g2: 7
    b2: 11
    a: 39
    b: 38
    c: 37
    d: 36
    e: 21
    lat: 33
    oe: 35
    clk: 34
