# Clockwise HUB75 Integration Example
# This example shows how to use the Clockwise component with HUB75 Matrix Display

esphome:
  name: clockwise-hub75
  friendly_name: Clockwise HUB75 Clock

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your-encryption-key-here"

ota:
  - platform: esphome
    password: "your-ota-password-here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# External components
external_components:
  # Stuart Parmenter's HUB75 ESPHome component
  - source: github://stuartparmenter/hub75-esphome
    components: [hub75]
  # Clockwise HUB75 integration component from GitHub
  - source: github://aschoelzhorn/clockwise-esphome@feature/use_hub75_component
    components: [clockwise_hub75]
    refresh: 1h

# HUB75 Matrix Display Configuration
display:
  - platform: hub75
    id: matrix_display
    panel_width: 64
    panel_height: 32
    brightness: 128
    bit_depth: 8
    min_refresh_rate: 60
    double_buffer: false
    
    # Pin configuration - adjust for your hardware
    r1_pin: GPIO25
    g1_pin: GPIO26
    b1_pin: GPIO27
    r2_pin: GPIO14
    g2_pin: GPIO12
    b2_pin: GPIO13
    a_pin: GPIO23
    b_pin: GPIO19
    c_pin: GPIO5
    d_pin: GPIO17
    lat_pin: GPIO4
    oe_pin: GPIO15
    clk_pin: GPIO16
    
    # Disable lambda since clockwise component will handle rendering
    update_interval: never

# Clockwise Integration Component
clockwise_hub75:
  id: clockwise_main
  hub75_id: matrix_display
  clockface_type: PACMAN
  initial_brightness: 128

# Home Assistant Entities
number:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    name: "Display Brightness"
    icon: mdi:brightness-5
    min_value: 0
    max_value: 255
    step: 1

switch:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    name: "Display Power"
    icon: mdi:power

select:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    name: "Clockface"
    icon: mdi:clock-outline