# Clockwise HUB75 Clock - ESPHome Configuration
# Complete configuration for ESP32 with HUB75 RGB LED Matrix Display

substitutions:
  device_name: clockwise-hub75
  friendly_name: Clockwise HUB75 Clock
  
  # WiFi credentials (use secrets.yaml for production)
  wifi_ssid: "YourWiFiSSID"
  wifi_password: "YourWiFiPassword"
  
  # Display settings
  panel_width: "64"
  panel_height: "32"
  initial_brightness: "128"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "Clockwise Clock with HUB75 Matrix Display"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: DEBUG
  logs:
    component: DEBUG
    hub75: DEBUG
    clockwise_hub75: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi configuration
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Web server for debugging (optional - remove in production for better performance)
web_server:
  port: 80

# Time component for clock functionality
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/New_York  # Change to your timezone
    on_time_sync:
      then:
        - logger.log: "Time synchronized with Home Assistant"

# External components
external_components:
  # Stuart Parmenter's HUB75 ESPHome component
  - source: github://stuartparmenter/hub75-esphome
    components: [hub75]
    refresh: 1d
  # Clockwise HUB75 integration component from feature branch
  - source: github://aschoelzhorn/clockwise-esphome@feature/use_hub75_component
    components: [clockwise_hub75]
    refresh: 1h

# HUB75 Matrix Display Configuration
display:
  - platform: hub75
    id: matrix_display
    
    # Panel dimensions
    panel_width: ${panel_width}
    panel_height: ${panel_height}
    
    # Display settings
    brightness: ${initial_brightness}
    bit_depth: 8
    min_refresh_rate: 60
    double_buffer: false
    
    # Hardware configuration
    shift_driver: GENERIC  # Options: GENERIC, FM6126A, ICN2038S, FM6124, MBI5124, DP3246
    scan_wiring: STANDARD_TWO_SCAN  # Options: STANDARD_TWO_SCAN, FOUR_SCAN_16PX_HIGH, etc.
    
    # Pin configuration - ESP32 DevKit default pins
    # Adjust these to match your hardware setup
    r1_pin: GPIO25
    g1_pin: GPIO26
    b1_pin: GPIO27
    r2_pin: GPIO14
    g2_pin: GPIO12
    b2_pin: GPIO13
    a_pin: GPIO23
    b_pin: GPIO19
    c_pin: GPIO5
    d_pin: GPIO17
    # e_pin: GPIO18  # Only needed for 64px high panels (1/32 scan)
    lat_pin: GPIO4
    oe_pin: GPIO15
    clk_pin: GPIO16
    
    # Timing configuration (optional - use defaults for most panels)
    clock_speed: 20MHZ  # Options: 8MHZ, 10MHZ, 16MHZ, 20MHZ
    # latch_blanking: 1
    # clock_phase: false  # Set to true for MBI5124 driver
    
    # Disable lambda since clockwise component handles rendering
    update_interval: never

# Clockwise Integration Component
clockwise_hub75:
  id: clockwise_main
  hub75_id: matrix_display
  clockface_type: PACMAN  # Options: PACMAN, MARIO, CLOCK
  initial_brightness: ${initial_brightness}

# Home Assistant Entities

# Brightness Control (0-255)
number:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    id: display_brightness
    name: "Display Brightness"
    icon: mdi:brightness-5
    entity_category: config
    mode: slider

# Power Control
switch:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    id: display_power
    name: "Display Power"
    icon: mdi:power
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON

# Clockface Selection
select:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    id: clockface_selector
    name: "Clockface"
    icon: mdi:clock-outline
    entity_category: config

# Status indicators (optional)
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic
    
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic

  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic

# Restart button (for debugging)
button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic

  - platform: safe_mode
    name: "Safe Mode Boot"
    entity_category: diagnostic