# Clockwise HUB75 Clock - Multi-Panel Configuration
# Example: 2×1 horizontal panel chain (128×32 pixels)

substitutions:
  device_name: clockwise-hub75-wide
  friendly_name: Clockwise Wide Display
  
  # WiFi credentials
  wifi_ssid: "YourWiFiSSID"
  wifi_password: "YourWiFiPassword"
  
  # Multi-panel display settings
  panel_width: "64"
  panel_height: "32"
  layout_cols: "2"  # 2 panels horizontally
  layout_rows: "1"
  initial_brightness: "128"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "Clockwise Clock with Multi-Panel HUB75 Display"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi configuration
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${device_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Time component
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/New_York

# External components
external_components:
  - source: github://stuartparmenter/hub75-esphome
    components: [hub75]
    refresh: 1d
  - source: github://aschoelzhorn/clockwise-esphome@feature/use_hub75_component
    components: [clockwise_hub75]
    refresh: 1h

# HUB75 Multi-Panel Display Configuration
display:
  - platform: hub75
    id: matrix_display
    
    # Single panel dimensions
    panel_width: ${panel_width}
    panel_height: ${panel_height}
    
    # Multi-panel layout
    layout_cols: ${layout_cols}  # 2 panels side by side
    layout_rows: ${layout_rows}
    layout: HORIZONTAL  # Options: HORIZONTAL, TOP_LEFT_DOWN, TOP_LEFT_DOWN_ZIGZAG, etc.
    
    # Total display size will be: 128×32 pixels (2×64 × 32)
    
    # Display settings
    brightness: ${initial_brightness}
    bit_depth: 8
    min_refresh_rate: 60
    double_buffer: false
    
    # Hardware configuration
    shift_driver: GENERIC
    scan_wiring: STANDARD_TWO_SCAN
    
    # Pin configuration - same pins drive all panels in chain
    r1_pin: GPIO25
    g1_pin: GPIO26
    b1_pin: GPIO27
    r2_pin: GPIO14
    g2_pin: GPIO12
    b2_pin: GPIO13
    a_pin: GPIO23
    b_pin: GPIO19
    c_pin: GPIO5
    d_pin: GPIO17
    lat_pin: GPIO4
    oe_pin: GPIO15
    clk_pin: GPIO16
    
    clock_speed: 20MHZ
    update_interval: never

# Clockwise Integration Component
clockwise_hub75:
  id: clockwise_main
  hub75_id: matrix_display
  clockface_type: PACMAN
  initial_brightness: ${initial_brightness}

# Home Assistant Entities
number:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    name: "Display Brightness"
    icon: mdi:brightness-5
    entity_category: config
    mode: slider

switch:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    name: "Display Power"
    icon: mdi:power
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON

select:
  - platform: clockwise_hub75
    clockwise_hub75_id: clockwise_main
    name: "Clockface"
    icon: mdi:clock-outline
    entity_category: config

# Status indicators
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic

button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic